name: student_app
description: "IIITNR Attendance Student App"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  lucide_icons: ^0.257.0
  intl: ^0.19.0
  
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.2
  google_sign_in: ^6.2.2
  http: ^1.2.2
  mobile_scanner: ^5.2.3
  geolocator: ^10.0.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.4
  flutter_secure_storage: ^9.2.2
  device_info_plus: ^10.1.2
  local_auth: ^2.3.0


# Forces compatible Android plugin version
dependency_overrides:
  geolocator_android: 4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/home-logo.png
    - assets/logo.png
    - assets/404error.jpg
    - assets/withoutlogo.png
    - assets/apklogo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/apklogo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/apklogo.png"